### ISSUE TITLE
Issue with Tx Broadcast?

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/poet#302]
Some works in app.po.et are starting to display `Unconfirmed`, which means that the information of the bitcoin transaction wasn't found.

Example: https://app.po.et/works/5254b3c5b336786c0991987d650c6f47c3b3b3ff5cf4ce968e596c17d0b4a642

This article was published 4 days ago, yet there are more recent articles that have been confirmed properly. 

What's going on?

**Comment by lautarodragan** [comment]
Can use the following query to find out what works are still unconfirmed:

```sql
select distinct work.id, work."displayName", to_timestamp(attribute.value::decimal / 1000) as datePublished
from work 
left join claim_info on (work.id = claim_info.hash) 
left join attribute on (attribute.claim = work.id)
where claim_info.hash is null 
and attribute.key = 'datePublished'
order by to_timestamp((attribute.value::decimal) / 1000);
```

And this to just count them:

```sql
select count(work.id)
from work 
left join claim_info on (work.id = claim_info.hash)
where claim_info.hash is null;
```

Currently outputting 

```
                                id                                |                                                           displayName                                                            |     datepublished      
------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------------------------
 080fcc620f86a94b48b61e772c9cb5576c6d9731be99c30313bf60c15b492e63 | Blockchain and Bitstamp Customers Can Now Use Ether                                                                              | 2017-08-17 16:48:47+00
 a4b59fb75e63565d72e02e53227b1ded4d582041d605fac436e9d53aa31ebb97 | Presearch Uses Ethereum Blockchain and AI to Challenge Google on Its Own Turf                                                    | 2017-08-17 17:44:46+00
 2d6390fcd2a0d03edd52b4c0e108e852904f8b8f4e1b9e147d2c757a8c977852 | Sony and IBM Join Forces to Put Student Achievement on the Blockchain                                                            | 2017-08-17 20:29:02+00
 163bf792008fc7aecd071c8feb4956fc902d22c276d321890f69a0329c2a2b85 | Bitcoin Price Analysis: Long and Short Squeezes Shape a Weakening All-Time High                                                  | 2017-08-17 20:57:56+00
 04ab0575083159e2ccf26257df523cad2904945f8adf4c98fa78c6a07add0c35 | Daily Roundup – August 17, 2017                                                                                                  | 2017-08-18 03:58:03+00
 97e5acd91913443399f87ac34533a8ad674b69c2bd002ec660318193fc3fc1fa | HiddenWallet and Samourai Wallet Join Forces to Make Bitcoin Private With ZeroLink                                               | 2017-08-18 17:23:43+00
 443d1f60068b85980c257f2122a3c121db6c170670399154075aaf75a59bcb81 | Musicoin: A music industry where artists thrive and listeners are rewarded                                                       | 2017-08-18 18:57:06+00
 5b77cea2a419c99ac652236df3b3d8daa3795d591d29ac91d03fe003cacc6e66 | Could blockchain technology help stabilize oil prices?                                                                           | 2017-08-18 22:41:19+00
 2bd3f12e43254f0afffaeeaec79f4def8973a1e3d9a3a9d805d7cdbb2c5f7c28 | A Bitcoin Social Media Storm Hit BitPay This Week: Here's Why                                                                    | 2017-08-19 15:13:04+00
 184bff8ec8fc5210c86c094827e7097f99dc6fd9764ea4db0b8d2ea88459cdab | UTRUST Brings Consumer Protections to Cryptocurrencies, Announces Pre ICO                                                        | 2017-08-21 07:46:20+00
 59007d1f718980d6ec637b637d766ae1daf3ab8aaa1d708750ecbdd0691f9b3f | HappiStar Launches “Be HappiStar’s Most Shining Star!” Bonus                                                                     | 2017-08-21 07:53:52+00
 f746a6762d541857f805c7fb0cebdddb4aca054696e21ed3f094fe94d70d1ea2 | Bankera Announces Pre-ICO Details for its Revolutionary Blockchain Based Regulated Bank                                          | 2017-08-21 13:40:10+00
 8bed2f650ff3a6e9fdc4feda6cd40f46bd751347d5a2837217d2f1af89f26971 | AMBROSUS Partners with TREK THERAPEUTICS to Develop a Blockchain-powered Method to Track Quality in Pharmaceutical Manufacturing | 2017-08-21 13:49:21+00
 8c398981b58d79f4f5bfcc87fcd9defa3ed85aee52a3a647e61b290796e6f85e | Startup Societies Summit and surrounding festivities                                                                             | 2017-08-21 15:43:07+00
 efa3655f85d29ed7c079d64ee791bed30e5b4e5d2a9b204a8b1f40c4a22a257c | AMD Releases Beta Graphics Driver for Better Cryptocurrency Mining                                                               | 2017-08-21 19:08:12+00
 94c1d3c33c276cc25ea8e6020a1eb68c9f31b8e170e55cf70e8aed2cb217a605 | Monero Price Hits Record High of $95 Amid Rumors of Debut at Bithumb Exchange                                                    | 2017-08-21 20:28:47+00
 e66c6cf4784113e33c35af602cbffab96125d9aa58edc6fe908a7a5ff3b1c4da | Is Blockchain Technology the Future of the Payments Industry?                                                                    | 2017-08-21 20:30:44+00
 ad9cea7c52417e1ac965390c0922df75070509d213f955a139ba727a24cca32d | Daily Roundup – August 21, 2017                                                                                                  | 2017-08-22 01:14:02+00
 af2f453ea7df34c3db301c726fa5034dd2b94cd52cf076e79151e2d424b6e42c | Interview with Brian Robertson of Holacracy                                                                                      | 2017-08-22 01:40:58+00
 eb900f141226fb30c6a74af475d762c5054e0675f1f69125cc1d2a7176fa781c | GoldMint to Launch ICO with Early Bird Bonuses                                                                                   | 2017-08-22 06:12:42+00
 2d3f056643a0d926e61b2350ead9889ef466622443b6ad2d074cef66ed3e683b | Bitcoin Price Downs Below $4,000, Bitcoin Cash and Ethereum Are Also Not At Rest                                                 | 2017-08-22 07:15:20+00
 58fda45ee43f8521842de4a6eb616d0c9ad182111789090501d2bcfde008b2b3 | Сrypto Project GoldMint to Launch ICO with Early Bird Bonuses                                                                    | 2017-08-22 11:40:16+00
 2c729726d4578aa1c986e81c4fd4bdb4c6644254e43b959f502fac81ed10f134 | New 3D Printed Material Makes Future Homes More Energy Efficient                                                                 | 2017-08-22 13:00:22+00
 bb9285436013266594dcdc3031bc37babbb243a8c27baf8555378c8e96323e9b | BlockRx™ Announces Powerhouse Partners Before the First Pharmaceutical ICO Offering Hits the Market                              | 2017-08-22 13:30:39+00
 35fcfee8619be396c921070456483afe6e66c9e2ba8d182b096e041f6a8e551f | Elon Musk Signs Petition Demanding Ban on Killer Robots                                                                          | 2017-08-22 14:00:59+00
 03d054b30e451f493724c1de5bd94b93bbf79836cb34b6a1bd08bb7e385594ec | Lordmancer II – Pre ICO of a Mobile MMORPG Promising to Let its Players Mine Cryptocurrency Starts on August 21                  | 2017-08-22 14:30:13+00
 378e1f79c1df33d6c1b96e7a2470213932899c1913250c8dfda3ddf0ca88e5b2 | Gregory Maxwell Claims Bitcoin Cash Mining Income Is Inflated                                                                    | 2017-08-22 15:00:01+00
 0741a337bc0e4c3880c7324050264d53d39a18b2575d8ba3079f622181ba4581 | ViaBTC Mining Pool Will Automatically Switch Between BTC and BCH Mining                                                          | 2017-08-22 16:00:08+00
 d79707fc505620662c97654be55f20df546600915463f1fe473fe0378c7051fa | LAToken Lets Cryptocurrency Economy Invade Trillion Dollar Markets                                                               | 2017-08-22 16:40:03+00
 672d10de9008a08ce4fd65085e222083c358975e3b814b7a1564b132c67fe092 | Faketoken Android Malware Can Steal Victims’ Calls, Texts, and Credit Cards                                                      | 2017-08-22 17:00:30+00
 7b47a726bffa39fa9b26d08ec00c5df69ff39b641b06ab9953be3b16ab75a9a6 | IBM Partners with Walmart, Nestle and Other Food Giants to Improve Food Safety Using Blockchain                                  | 2017-08-22 17:02:18+00
 b483c23bc0895c36b143d4b8305e1267297ae24afd35632b529b049cb432a486 | Cash Poker Pro Is a Modern Decentralized Poker Room                                                                              | 2017-08-22 17:30:17+00
 5dfbcfa7d82355aa359a3e72d320b10c99bbef8733ab752c4725fcfc23882b4f | Op Ed: A Cryptographic Design Perspective of Blockchains: From Bitcoin to Ouroboros                                              | 2017-08-22 17:35:44+00
 addf6e09013429c1143b83b2c1468a4bb5849d729d2560bee93e6e3b00c9ad3b | What is Zerolink?                                                                                                                | 2017-08-22 18:00:08+00
 8c2f545e47ae84d01177dabb5a2dfb29398502c280d402666cfc554344faf77d | Government driving South Korea’s blockchain progress                                                                             | 2017-08-22 18:43:55+00
 b4947b82ee09a82601bf3dd9817c27b79b1963f9775946491f95ebbae22920fb | Plex Users Outraged Over Company’s Plans to Collect More Information                                                             | 2017-08-22 19:00:59+00
 0c5507107e378b876ae82ca2f4363afd48d7bd2085f0a4c786429f3c7ed62f8b | Why Bcash Mining Shouldn't Affect Bitcoin Much (But Bitcoin Mining Could Ruin Bcash)                                             | 2017-08-22 20:11:07+00
 554ba3d3a273c92915d5d995654009018a1fe32b1b358da6a2e5dc096f71cd07 | Daily Roundup – September 1, 2017                                                                                                | 2017-09-02 19:17:13+00
 fb71350cd118647bd1a3cbd1c90697842ef5705f12586408e4d841035c6b4c69 | Buy a Lamborghini With Bitcoin in Newport Beach                                                                                  | 2017-09-03 16:00:46+00
 63fd0badea4590daa1e3657969a0e48972b7960a945d485999c7d025bd2a9592 | UTRUST Pre-ICO Sells Out Raising $1.5M in 90 Minutes, Ahead of Its Public Fundraising on September 20                            | 2017-09-04 08:51:39+00
 95a859264a24788a2c598b594a894bad3b2de706722c16c13f630a5826734451 | Bitcoin Price Falls Below $4,300 After China’s Central Bank Banned All ICOs                                                      | 2017-09-04 12:04:36+00
 7eeb057544c0a4d97726c1f5d214bccfed23e52e141dec4380a4764d35396176 | A hundred years of Crypto Anarchy                                                                                                | 2017-09-04 12:24:40+00
 3770ba5317484e6484374cbb648e5b877489999ad10c24e0040d96e7c743acb1 | Snovio – Lead Generation and Sourcing Platform – Has Been Released                                                               | 2017-09-04 12:55:29+00
 0de413bcd16ddb10759d71212cb9b5f754ccb6f738f39829023013ed92273e53 | “Troll” Ransomware Aims to Brick Infected Devices                                                                                | 2017-09-04 13:00:47+00
 a82820298ef1d98580a3ef89a23e464c874bd6874476e9b4b9fa767c68bb337f | Troll Ransomware Aims to Brick Infected Devices                                                                                  | 2017-09-04 13:00:47+00
 daf4932a180037d5e04a17cacf537b3f7beb0229f7e0e98867540721ba6b3072 | The Number of Bitcoin Network SegWit Transactions Remains Very Small                                                             | 2017-09-04 15:00:58+00
 5254b3c5b336786c0991987d650c6f47c3b3b3ff5cf4ce968e596c17d0b4a642 | Tasty New Features of Android Oreo                                                                                               | 2017-09-04 19:59:58+00
 23d218d219df795a49374325a4df70a73b7d34758a1ffa0e0792d8d8a619752c | Blockchain-based YouTube has potential to be censorship-resistant alternative                                                    | 2017-09-04 20:44:29+00
 4dfadc9abb848796942cf14378ba5acd8c1bdb6652657818393923ada66b6d60 | NEO Price Bounces Back to $22 Thanks to 16% Gain Against Bitcoin                                                                 | 2017-09-05 11:33:38+00
 cb33a7c33516c01d52fd224d3504d9e5339c2fea88eb29e62dfe966ec25c278e | Viberate Completes Its ICO in Record Time, Vibe Token Will be Listed on October 6                                                | 2017-09-05 13:13:00+00
 4ba67be6d9fccc259bf5d60da1b94922e32ea7160ef14d91e97da942fdc4d6e7 | How Ethbet Plans to Take Over the Dicing Industry                                                                                | 2017-09-05 14:30:07+00
(51 rows)
```

**Comment by lautarodragan** [comment]
https://app.po.et/api/explorer/works/080fcc620f86a94b48b61e772c9cb5576c6d9731be99c30313bf60c15b492e63 could be in https://test-insight.bitpay.com/tx/1bc4a6f0e1d4aeb0f38c09c685fe9228f4bf6a0b5e91dabbf89b7f0f0a3e983b

**Comment by lautarodragan** [comment]
```bash
$ scan-tx 1bc4a6f0e1d4aeb0f38c09c685fe9228f4bf6a0b5e91dabbf89b7f0f0a3e983b
Retrieving transaction 1bc4a6f0e1d4aeb0f38c09c685fe9228f4bf6a0b5e91dabbf89b7f0f0a3e983b
Transaction retrieved successfully.

Scanning transaction...

Found Po.et data:
{
  "transactionHash": "1bc4a6f0e1d4aeb0f38c09c685fe9228f4bf6a0b5e91dabbf89b7f0f0a3e983b",
  "outputIndex": 0,
  "prefix": "POET",
  "version": "0,0,0,2",
  "torrentHash": "9e392e799f338a6beb0ff0b76d119790c4156119"
}

$ cd 9e392e799f338a6beb0ff0b76d119790c4156119
$ ls
a8da68fdbc944ed1bf5a178d4195aeecca8de36d2e0b7f4db1cf24da7ea69163
$ cat a8da68fdbc944ed1bf5a178d4195aeecca8de36d2e0b7f4db1cf24da7ea69163 | grep https://bitcoinmagazine.com/articles/blockchain-and-bitstamp-customers-can-now-use-ether/
Binary file (standard input) matches
```
So this means we have the work in the database AND the torrent file correctly, and the information is out there in the blockchain.

Looking into the database...

```sql
poet=# select * from block_processed where hash='000000000003900fe3cc34621ff6e2c0e91bd92ab26b20f990ad338367d99ca2';
 id | hash | parentHash | height | transactionCount | timeProcessed | errorMessage | orphaned 
----+------+------------+--------+------------------+---------------+--------------+----------
(0 rows)
```

Which seems to mean that everything was stored correctly everywhere, but the node skipped processing of https://test-insight.bitpay.com/block/000000000003900fe3cc34621ff6e2c0e91bd92ab26b20f990ad338367d99ca2 for some reason.

**Comment by lautarodragan** [comment]
I'm betting these errors are the culprit:

```
bitcoin-scanner_1    | Error publishing Error: Queue is being used
bitcoin-scanner_1    |     at Queue.lockConnection (/poet/src/queue.ts:169:13)
bitcoin-scanner_1    |     at Queue.<anonymous> (/poet/src/queue.ts:137:12)
bitcoin-scanner_1    |     at Generator.next (<anonymous>)
bitcoin-scanner_1    |     at fulfilled (/poet/src/queue.ts:4:58)
bitcoin-scanner_1    |     at <anonymous>
bitcoin-scanner_1    |     at process._tickDomainCallback (internal/process/next_tick.js:208:7) Error: Queue is being used
bitcoin-scanner_1    |     at Queue.lockConnection (/poet/src/queue.ts:169:13)
bitcoin-scanner_1    |     at Queue.<anonymous> (/poet/src/queue.ts:137:12)
bitcoin-scanner_1    |     at Generator.next (<anonymous>)
bitcoin-scanner_1    |     at fulfilled (/poet/src/queue.ts:4:58)
bitcoin-scanner_1    |     at <anonymous>
bitcoin-scanner_1    |     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
bitcoin-scanner_1    | Could not publish block Error: Queue was not being used
bitcoin-scanner_1    |     at Queue.unlockConnection (/poet/src/queue.ts:178:13)
bitcoin-scanner_1    |     at Queue.<anonymous> (/poet/src/queue.ts:146:12)
bitcoin-scanner_1    |     at Generator.next (<anonymous>)
bitcoin-scanner_1    |     at fulfilled (/poet/src/queue.ts:4:58)
bitcoin-scanner_1    |     at <anonymous>
bitcoin-scanner_1    |     at process._tickDomainCallback (internal/process/next_tick.js:208:7) Error: Queue was not being used
bitcoin-scanner_1    |     at Queue.unlockConnection (/poet/src/queue.ts:178:13)
bitcoin-scanner_1    |     at Queue.<anonymous> (/poet/src/queue.ts:146:12)
bitcoin-scanner_1    |     at Generator.next (<anonymous>)
bitcoin-scanner_1    |     at fulfilled (/poet/src/queue.ts:4:58)
bitcoin-scanner_1    |     at <anonymous>
bitcoin-scanner_1    |     at process._tickDomainCallback (internal/process/next_tick.js:208:7)
bitcoin-scanner_1    | (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1255): Error: Queue is being used
```

One possible way to proceed is to try and attack this errors.
Another would be to change how the system works: instead of simply scanning every bitcoin block one by one, also checking which are missing in the database.
Also, an upgrade could be made in the system: it's currently scanning one by one in series. It could process them in parallel up to N at the same time. With N = 2 or 3 we would probably see a huge increase in scanning speed without much impact on performance.
